name: Draft a new release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: The Tag to create for this release
        type: string
        required: true
      name:
        description: The name of the release (OPTIONAL)
        type: string
        required: false
jobs:
  draft_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v7
      - name: Build the new README
        run: ./build-readme.md
      - name: Draft release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "gitlab-readme.md"
          body: "# Blog release ${{ inputs.tag }}\n\nTODO: Explain what changed here"
          draft: true
          generateReleaseNotes: true
          artifactErrorsFailBuild: true
          replacesArtifacts: true
          updateOnlyUnreleased: true
          tag: ${{ inputs.tag }}
          name: ${{ inputs.name }}
